[tool.poetry]
name = "deep_volatility_models"
version = "0.0.1"
description = "Volatility models for stock prices using deep learning and mixture models."
authors = ["Mark A Wicks <mawicks@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8,<3.10"
pandas = "^1.2.3"
torch = "^1.11.0"
yfinance = "^0.1.59"
matplotlib = "^3.4.0"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.7b0"

[build-system]
requires = ["poetry-core>=1.0.0a6", "setuptools>=46.0.0"]
build-backend = "poetry.core.masonry.api"
